name: CI - HTML validation

on:
  push:
    branches: [ "main" ]

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Download Nu HTML Validator (zip)
        run: |
          curl -L https://github.com/validator/validator/releases/latest/download/vnu.linux.zip -o vnu.zip
          unzip vnu.zip
          ls -lh vnu-runtime-image/

      - name: Validate HTML
        run: ./vnu-runtime-image/bin/vnu --errors-only index.html
